version: '2'
services:
    mongodb-app:
        image: mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=mongodb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mongodb-mongodb:
        extends:
            file: mongodb.yml
            service: mongodb-mongodb
